name: jtl
description: JetLeaf Template Language â€” a lightweight template engine for generating HTML, text, and dynamic content.
version: 1.0.9

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jtl
issue_tracker: https://github.com/jetleaf/jtl/issues
documentation: https://jetleaf.hapnium.com/docs/jtl

topics:
  - templates
  - rendering
  - jetleaf
  - html
  - dynamic-content

keywords:
  - jetleaf
  - templates
  - rendering
  - html
  - templating

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.1.0
  jetleaf_logging: ^1.1.0

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0